inherit_from: .rubocop_todo.yml
require: rubocop-rspec

RSpec/ContextWording:
  Enabled: false # too dogmatic

RSpec/ExampleLength:
  Max: 25

# we like 'expect(x).to receive' better than 'have_received'
RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 4 # default: 3

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
